export {
  Chat,
  ChatHeader,
  ChatTitle,
  ChatDescription,
  ChatMessages,
  ChatMessage,
  ChatInput,
  ChatActions,
  TypingIndicator,
  type ChatProps,
  type ChatHeaderProps,
  type ChatTitleProps,
  type ChatDescriptionProps,
  type ChatMessagesProps,
  type ChatMessageProps,
  type ChatInputProps,
  type ChatActionsProps,
  type TypingIndicatorProps,
  type Message,
  type TypingUser,
} from './chat';

export {
  BasicChatDemo,
  ChatWithHeaderDemo,
  ChatWithAvatarsDemo,
  ChatWithTimestampsDemo,
  ReadOnlyChatDemo,
  ChatWithActionsDemo,
  CustomStyledChatDemo,
  TypingIndicatorDemo,
} from './chat-demos'; 