#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

bash ./scripts/sync-css-tokens.sh
bash ./scripts/build-components.sh
bash ./scripts/sync-icons.sh

git add \
	public/registry/components.json \
	public/registry/css/index.css \
	public/registry/lib/icons.ts
